// GENERATED from page_timings.csv + measured ogg durations (Sonata 6 estimated, silent)
// Page `time` = seconds on the sonata's own audio clock when the page begins.
export const sonatas = [
    {
        id: 1,
        name: 'Barley',
        title: 'Sonata 1 - Barley',
        audio: '/audio/Sonata 1.ogg',
        duration: 465.158,
        silent: false,
        pages: [
            { file: 'music_page_007.jpg', time: 0.0 },
            { file: 'music_page_008.jpg', time: 56.1 },
            { file: 'music_page_009.jpg', time: 116.0 },
            { file: 'music_page_010.jpg', time: 190.0 },
            { file: 'music_page_011.jpg', time: 218.8 },
            { file: 'music_page_012.jpg', time: 252.3 },
            { file: 'music_page_013.jpg', time: 289.9 },
            { file: 'music_page_014.jpg', time: 390.5 },
            { file: 'music_page_015.jpg', time: 426.6 },
        ],
    },
    {
        id: 2,
        name: 'Wheat',
        title: 'Sonata 2 - Wheat',
        audio: '/audio/Sonata 2.ogg',
        duration: 516.73,
        silent: false,
        pages: [
            { file: 'music_page_017.jpg', time: 0.0 },
            { file: 'music_page_018.jpg', time: 53.0 },
            { file: 'music_page_019.jpg', time: 100.0 },
            { file: 'music_page_020.jpg', time: 145.8 },
            { file: 'music_page_021.jpg', time: 204.3 },
            { file: 'music_page_022.jpg', time: 245.9 },
            { file: 'music_page_023.jpg', time: 285.9 },
            { file: 'music_page_024.jpg', time: 324.3 },
            { file: 'music_page_025.jpg', time: 369.2 },
            { file: 'music_page_026.jpg', time: 424.4 },
            { file: 'music_page_027.jpg', time: 466.5 },
        ],
    },
    {
        id: 3,
        name: 'Olives',
        title: 'Sonata 3 - Olives',
        audio: '/audio/Sonata 3.ogg',
        duration: 624.789,
        silent: false,
        pages: [
            { file: 'music_page_029.jpg', time: 0.0 },
            { file: 'music_page_030.jpg', time: 40.9 },
            { file: 'music_page_031.jpg', time: 74.9 },
            { file: 'music_page_032.jpg', time: 105.0 },
            { file: 'music_page_033.jpg', time: 135.0 },
            { file: 'music_page_034.jpg', time: 204.8 },
            { file: 'music_page_035.jpg', time: 278.5 },
            { file: 'music_page_036.jpg', time: 326.0 },
            { file: 'music_page_037.jpg', time: 370.2 },
            { file: 'music_page_038.jpg', time: 421.1 },
            { file: 'music_page_039.jpg', time: 471.5 },
            { file: 'music_page_040.jpg', time: 524.0 },
            { file: 'music_page_041.jpg', time: 555.9 },
            { file: 'music_page_042.jpg', time: 586.5 },
        ],
    },
    {
        id: 4,
        name: 'Dates',
        title: 'Sonata 4 - Dates',
        audio: '/audio/Sonata 4.ogg',
        duration: 543.836,
        silent: false,
        pages: [
            { file: 'music_page_043.jpg', time: 0.0 },
            { file: 'music_page_044.jpg', time: 59.0 },
            { file: 'music_page_045.jpg', time: 111.8 },
            { file: 'music_page_046.jpg', time: 160.5 },
            { file: 'music_page_047.jpg', time: 214.2 },
            { file: 'music_page_048.jpg', time: 274.7 },
            { file: 'music_page_049.jpg', time: 321.5 },
            { file: 'music_page_050.jpg', time: 358.6 },
            { file: 'music_page_051.jpg', time: 398.9 },
            { file: 'music_page_052.jpg', time: 437.8 },
            { file: 'music_page_053.jpg', time: 471.6 },
            { file: 'music_page_054.jpg', time: 505.4 },
        ],
    },
    {
        id: 5,
        name: 'Pomegranates',
        title: 'Sonata 5 - Pomegranates',
        audio: '/audio/Sonata 5.ogg',
        duration: 673.826,
        silent: false,
        pages: [
            { file: 'music_page_055.jpg', time: 0.0 },
            { file: 'music_page_056.jpg', time: 62.9 },
            { file: 'music_page_057.jpg', time: 115.3 },
            { file: 'music_page_058.jpg', time: 158.5 },
            { file: 'music_page_059.jpg', time: 196.6 },
            { file: 'music_page_060.jpg', time: 234.6 },
            { file: 'music_page_061.jpg', time: 272.7 },
            { file: 'music_page_062.jpg', time: 310.8 },
            { file: 'music_page_063.jpg', time: 353.0 },
            { file: 'music_page_064.jpg', time: 385.1 },
            { file: 'music_page_065.jpg', time: 417.2 },
            { file: 'music_page_066.jpg', time: 472.2 },
            { file: 'music_page_067.jpg', time: 569.0 },
        ],
    },
    {
        id: 6,
        name: 'Figs',
        title: 'Sonata 6 - Figs (estimated, no audio)',
        audio: null,
        duration: 738.0,
        silent: true,
        pages: [
            { file: 'music_page_069.jpg', time: 0.0 },
            { file: 'music_page_070.jpg', time: 44.2 },
            { file: 'music_page_071.jpg', time: 88.3 },
            { file: 'music_page_072.jpg', time: 130.3 },
            { file: 'music_page_073.jpg', time: 174.4 },
            { file: 'music_page_074.jpg', time: 216.4 },
            { file: 'music_page_075.jpg', time: 269.3 },
            { file: 'music_page_076.jpg', time: 327.0 },
            { file: 'music_page_077.jpg', time: 375.9 },
            { file: 'music_page_078.jpg', time: 426.7 },
            { file: 'music_page_079.jpg', time: 474.6 },
            { file: 'music_page_080.jpg', time: 514.1 },
            { file: 'music_page_081.jpg', time: 556.4 },
            { file: 'music_page_082.jpg', time: 598.7 },
            { file: 'music_page_083.jpg', time: 647.8 },
            { file: 'music_page_084.jpg', time: 691.9 },
        ],
    },
    {
        id: 7,
        name: 'Grapes',
        title: 'Sonata 7 - Grapes',
        audio: '/audio/Sonata 7.ogg',
        duration: 669.827,
        silent: false,
        pages: [
            { file: 'music_page_085.jpg', time: 0.0 },
            { file: 'music_page_086.jpg', time: 40.5 },
            { file: 'music_page_087.jpg', time: 82.1 },
            { file: 'music_page_088.jpg', time: 123.7 },
            { file: 'music_page_089.jpg', time: 168.7 },
            { file: 'music_page_090.jpg', time: 225.2 },
            { file: 'music_page_091.jpg', time: 289.1 },
            { file: 'music_page_092.jpg', time: 339.5 },
            { file: 'music_page_093.jpg', time: 382.5 },
            { file: 'music_page_094.jpg', time: 425.5 },
            { file: 'music_page_095.jpg', time: 471.2 },
            { file: 'music_page_096.jpg', time: 516.9 },
            { file: 'music_page_097.jpg', time: 554.7 },
            { file: 'music_page_098.jpg', time: 590.6 },
            { file: 'music_page_099.jpg', time: 628.4 },
        ],
    },
]

let offset = 0
let pageIndex = 0
export const timeline = sonatas.map((sonata) => {
    const pages = sonata.pages.map((page, i) => {
        const next = sonata.pages[i + 1]

        return {
            ...page,
            image: `/pages/${page.file}`,
            sonataId: sonata.id,
            sonataName: sonata.name,
            sonataTitle: sonata.title,
            silent: sonata.silent,
            pageInSonata: i + 1,
            snapIndex: pageIndex++,
            start: offset + page.time,
            duration: (next ? next.time : sonata.duration) - page.time,
        }
    })
    const entry = { ...sonata, offset, pages }
    offset += sonata.duration

    return entry
})

export const pages = timeline.flatMap((sonata) => sonata.pages)
export const totalDuration = offset
